---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[xmledit-test::default]
      - recipe[xmledit-test::idempotent]
      - recipe[xmledit-test::bulk]
    attributes:
